
apis:
  container: "http://172.16.0.204:8051/container"
  container_model: "http://172.16.0.204:8051/containermodel"
  update_endpoint: "http://172.16.0.204:8051/updateEndpoint"
  model_master_config: "http://172.16.0.204:8051/getModelMasterbyId"
  model_config: "http://172.16.0.204:8051/getModelConfigbyId"
minio:
  endpoint: 172.16.0.178:9000
  secret_key: ktIanRWzFYLkxuKV52uHn8t2K9xhsczfS74RUKUX
  access_key: 6uYsllVhmjkWALUCR5uD
  secure: False