sftp:
  host: "172.16.0.171"
  username: "aditya.singh"
  port: 22
  password: "Welcome#123"
  path: "/models" 
apis:
  container: "http://172.16.0.204:8000/container"
  container_model: "http://172.16.0.204:8000/containermodel"
  update_endpoint: "http://172.16.0.204:8000/updateEndpoint"
  model_master_config: "http://172.16.0.204:8000/getModelMasterbyId"
  model_config: "http://172.16.0.204:8000/getModelConfigbyId"
# minio:
#   endpoint: 172.16.0.178:9000
#   secret_key: ktIanRWzFYLkxuKV52uHn8t2K9xhsczfS74RUKUX
#   access_key: 6uYsllVhmjkWALUCR5uD
#   secure: False
minio:
  endpoint: 172.16.0.170:9000
  secret_key: yMHbGFngNM5OnuWFj5lUDBJozEjryGAPBeF34WuG
  access_key: R8mQTw7uevt178G216KM
  secure: False
